"""Country detection from phone number prefixes"""

COUNTRY_PREFIXES = [
    # 4-digit prefixes
    {'code': 'SX', 'name': 'Sint Maarten', 'prefix': '1721'},
    {'code': 'AG', 'name': 'Antigua and Barbuda', 'prefix': '1268'},
    {'code': 'BB', 'name': 'Barbados', 'prefix': '1246'},
    {'code': 'BS', 'name': 'Bahamas', 'prefix': '1242'},
    {'code': 'DM', 'name': 'Dominica', 'prefix': '1767'},
    {'code': 'DO', 'name': 'Dominican Republic', 'prefix': '1809'},
    {'code': 'DO', 'name': 'Dominican Republic', 'prefix': '1829'},
    {'code': 'DO', 'name': 'Dominican Republic', 'prefix': '1849'},
    {'code': 'GD', 'name': 'Grenada', 'prefix': '1473'},
    {'code': 'JM', 'name': 'Jamaica', 'prefix': '1876'},
    {'code': 'KN', 'name': 'Saint Kitts and Nevis', 'prefix': '1869'},
    {'code': 'KY', 'name': 'Cayman Islands', 'prefix': '1345'},
    {'code': 'LC', 'name': 'Saint Lucia', 'prefix': '1758'},
    {'code': 'TC', 'name': 'Turks and Caicos', 'prefix': '1649'},
    {'code': 'TT', 'name': 'Trinidad and Tobago', 'prefix': '1868'},
    {'code': 'VC', 'name': 'Saint Vincent', 'prefix': '1784'},
    # 3-digit prefixes
    {'code': 'ARE', 'name': 'UAE', 'prefix': '971'},
    {'code': 'BHR', 'name': 'Bahrain', 'prefix': '973'},
    {'code': 'BGD', 'name': 'Bangladesh', 'prefix': '880'},
    {'code': 'BTN', 'name': 'Bhutan', 'prefix': '975'},
    {'code': 'KHM', 'name': 'Cambodia', 'prefix': '855'},
    {'code': 'CMR', 'name': 'Cameroon', 'prefix': '237'},
    {'code': 'CYP', 'name': 'Cyprus', 'prefix': '357'},
    {'code': 'GEO', 'name': 'Georgia', 'prefix': '995'},
    {'code': 'ISR', 'name': 'Israel', 'prefix': '972'},
    {'code': 'JOR', 'name': 'Jordan', 'prefix': '962'},
    {'code': 'KWT', 'name': 'Kuwait', 'prefix': '965'},
    {'code': 'LBN', 'name': 'Lebanon', 'prefix': '961'},
    {'code': 'MDV', 'name': 'Maldives', 'prefix': '960'},
    {'code': 'NPL', 'name': 'Nepal', 'prefix': '977'},
    {'code': 'OMN', 'name': 'Oman', 'prefix': '968'},
    {'code': 'QAT', 'name': 'Qatar', 'prefix': '974'},
    {'code': 'RWA', 'name': 'Rwanda', 'prefix': '250'},
    {'code': 'TJK', 'name': 'Tajikistan', 'prefix': '992'},
    {'code': 'UZB', 'name': 'Uzbekistan', 'prefix': '998'},
    # 2-digit prefixes (sorted by length desc, then by prefix desc)
    {'code': 'CZ', 'name': 'Czech Republic', 'prefix': '420'},
    {'code': 'MY', 'name': 'Malaysia', 'prefix': '60'},
    {'code': 'AU', 'name': 'Australia', 'prefix': '61'},
    {'code': 'ID', 'name': 'Indonesia', 'prefix': '62'},
    {'code': 'PH', 'name': 'Philippines', 'prefix': '63'},
    {'code': 'NZ', 'name': 'New Zealand', 'prefix': '64'},
    {'code': 'SG', 'name': 'Singapore', 'prefix': '65'},
    {'code': 'TH', 'name': 'Thailand', 'prefix': '66'},
    {'code': 'JP', 'name': 'Japan', 'prefix': '81'},
    {'code': 'KR', 'name': 'South Korea', 'prefix': '82'},
    {'code': 'VN', 'name': 'Vietnam', 'prefix': '84'},
    {'code': 'CN', 'name': 'China', 'prefix': '86'},
    {'code': 'TR', 'name': 'Turkey', 'prefix': '90'},
    {'code': 'IN', 'name': 'India', 'prefix': '91'},
    {'code': 'PK', 'name': 'Pakistan', 'prefix': '92'},
    {'code': 'LK', 'name': 'Sri Lanka', 'prefix': '94'},
    {'code': 'MM', 'name': 'Myanmar', 'prefix': '95'},
    {'code': 'BN', 'name': 'Brunei', 'prefix': '673'},
    {'code': 'TW', 'name': 'Taiwan', 'prefix': '886'},
    {'code': 'HK', 'name': 'Hong Kong', 'prefix': '852'},
    {'code': 'MO', 'name': 'Macau', 'prefix': '853'},
    {'code': 'KH', 'name': 'Cambodia', 'prefix': '855'},
    {'code': 'LA', 'name': 'Laos', 'prefix': '856'},
    {'code': 'EG', 'name': 'Egypt', 'prefix': '20'},
    {'code': 'ZA', 'name': 'South Africa', 'prefix': '27'},
    {'code': 'GR', 'name': 'Greece', 'prefix': '30'},
    {'code': 'NL', 'name': 'Netherlands', 'prefix': '31'},
    {'code': 'BE', 'name': 'Belgium', 'prefix': '32'},
    {'code': 'FR', 'name': 'France', 'prefix': '33'},
    {'code': 'ES', 'name': 'Spain', 'prefix': '34'},
    {'code': 'HU', 'name': 'Hungary', 'prefix': '36'},
    {'code': 'IT', 'name': 'Italy', 'prefix': '39'},
    {'code': 'RO', 'name': 'Romania', 'prefix': '40'},
    {'code': 'CH', 'name': 'Switzerland', 'prefix': '41'},
    {'code': 'AT', 'name': 'Austria', 'prefix': '43'},
    {'code': 'DK', 'name': 'Denmark', 'prefix': '45'},
    {'code': 'NO', 'name': 'Norway', 'prefix': '47'},
    {'code': 'PL', 'name': 'Poland', 'prefix': '48'},
    {'code': 'DE', 'name': 'Germany', 'prefix': '49'},
    {'code': 'PE', 'name': 'Peru', 'prefix': '51'},
    {'code': 'MX', 'name': 'Mexico', 'prefix': '52'},
    {'code': 'CU', 'name': 'Cuba', 'prefix': '53'},
    {'code': 'AR', 'name': 'Argentina', 'prefix': '54'},
    {'code': 'BR', 'name': 'Brazil', 'prefix': '55'},
    {'code': 'CL', 'name': 'Chile', 'prefix': '56'},
    {'code': 'CO', 'name': 'Colombia', 'prefix': '57'},
    {'code': 'VE', 'name': 'Venezuela', 'prefix': '58'},
    {'code': 'MY', 'name': 'Malaysia', 'prefix': '60'},
    {'code': 'AU', 'name': 'Australia', 'prefix': '61'},
    {'code': 'ID', 'name': 'Indonesia', 'prefix': '62'},
    {'code': 'PH', 'name': 'Philippines', 'prefix': '63'},
    {'code': 'NZ', 'name': 'New Zealand', 'prefix': '64'},
    {'code': 'SG', 'name': 'Singapore', 'prefix': '65'},
    {'code': 'TH', 'name': 'Thailand', 'prefix': '66'},
    {'code': 'JP', 'name': 'Japan', 'prefix': '81'},
    {'code': 'KR', 'name': 'South Korea', 'prefix': '82'},
    {'code': 'VN', 'name': 'Vietnam', 'prefix': '84'},
    {'code': 'CN', 'name': 'China', 'prefix': '86'},
    {'code': 'TR', 'name': 'Turkey', 'prefix': '90'},
    {'code': 'IN', 'name': 'India', 'prefix': '91'},
    {'code': 'PK', 'name': 'Pakistan', 'prefix': '92'},
    {'code': 'LK', 'name': 'Sri Lanka', 'prefix': '94'},
    {'code': 'MM', 'name': 'Myanmar', 'prefix': '95'},
    {'code': 'SA', 'name': 'Saudi Arabia', 'prefix': '966'},
    {'code': 'UA', 'name': 'Ukraine', 'prefix': '380'},
    {'code': 'IE', 'name': 'Ireland', 'prefix': '353'},
    {'code': 'PT', 'name': 'Portugal', 'prefix': '351'},
    {'code': 'SE', 'name': 'Sweden', 'prefix': '46'},
    {'code': 'FI', 'name': 'Finland', 'prefix': '358'},
    {'code': 'GB', 'name': 'United Kingdom', 'prefix': '44'},
    {'code': 'NG', 'name': 'Nigeria', 'prefix': '234'},
    {'code': 'KE', 'name': 'Kenya', 'prefix': '254'},
    {'code': 'TZ', 'name': 'Tanzania', 'prefix': '255'},
    {'code': 'UG', 'name': 'Uganda', 'prefix': '256'},
    {'code': 'ET', 'name': 'Ethiopia', 'prefix': '251'},
    {'code': 'SO', 'name': 'Somalia', 'prefix': '252'},
    {'code': 'DZ', 'name': 'Algeria', 'prefix': '213'},
    {'code': 'TN', 'name': 'Tunisia', 'prefix': '216'},
    {'code': 'LY', 'name': 'Libya', 'prefix': '218'},
    {'code': 'GH', 'name': 'Ghana', 'prefix': '233'},
    {'code': 'NE', 'name': 'Niger', 'prefix': '227'},
    {'code': 'TG', 'name': 'Togo', 'prefix': '228'},
    {'code': 'BJ', 'name': 'Benin', 'prefix': '229'},
    {'code': 'MR', 'name': 'Mauritania', 'prefix': '222'},
    {'code': 'ML', 'name': 'Mali', 'prefix': '223'},
    {'code': 'GN', 'name': 'Guinea', 'prefix': '224'},
    {'code': 'CI', 'name': 'Ivory Coast', 'prefix': '225'},
    {'code': 'BF', 'name': 'Burkina Faso', 'prefix': '226'},
    {'code': 'SN', 'name': 'Senegal', 'prefix': '221'},
    {'code': 'RU', 'name': 'Russia', 'prefix': '7'},
    {'code': 'US', 'name': 'United States', 'prefix': '1'},
    {'code': 'CA', 'name': 'Canada', 'prefix': '1'},
    {'code': 'AU', 'name': 'Australia', 'prefix': '61'},
    {'code': 'PG', 'name': 'Papua New Guinea', 'prefix': '675'},
    {'code': 'FJ', 'name': 'Fiji', 'prefix': '679'},
    {'code': 'CD', 'name': 'DR Congo', 'prefix': '243'},
    {'code': 'AO', 'name': 'Angola', 'prefix': '244'},
    {'code': 'CG', 'name': 'Congo', 'prefix': '242'},
    {'code': 'CM', 'name': 'Cameroon', 'prefix': '237'},
    {'code': 'YE', 'name': 'Yemen', 'prefix': '967'},
    {'code': 'IQ', 'name': 'Iraq', 'prefix': '964'},
    {'code': 'SY', 'name': 'Syria', 'prefix': '963'},
    {'code': 'PS', 'name': 'Palestine', 'prefix': '970'},
    {'code': 'IR', 'name': 'Iran', 'prefix': '98'},
    {'code': 'AF', 'name': 'Afghanistan', 'prefix': '93'},
    {'code': 'LK', 'name': 'Sri Lanka', 'prefix': '94'},
]

# Sort by prefix length descending for longest match
SORTED_PREFIXES = sorted(COUNTRY_PREFIXES, key=lambda x: x['prefix'], reverse=True)


def detect_country(phone_number: str) -> dict | None:
    if not phone_number:
        return None
    
    digits = ''.join(c for c in phone_number if c.isdigit())
    if not digits or len(digits) < 4:
        return None
    
    for country in SORTED_PREFIXES:
        if digits.startswith(country['prefix']):
            return {'code': country['code'], 'name': country['name']}
    
    return None
